name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v2

      - name:  Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name:  Terraform Init
        run: terraform init
        working-directory: terraform/

      - name:  Terraform Validate
        run: terraform validate
        working-directory: terraform/

      - name:  Terraform Plan
        run: terraform plan
        working-directory: terraform/
